# Generated by Django 5.0.1 on 2025-12-22 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lt', models.CharField(max_length=100, verbose_name='Name (Lithuanian)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this daily menu (YYYY-MM-DD)', unique=True, verbose_name='Date')),
                ('published', models.BooleanField(default=False, help_text='Whether this menu is visible to customers', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Menu',
                'verbose_name_plural': 'Daily Menus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lt', models.CharField(max_length=200, verbose_name='Name (Lithuanian)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('ingredients_lt', models.TextField(blank=True, help_text='List of ingredients in Lithuanian', verbose_name='Ingredients (Lithuanian)')),
                ('ingredients_en', models.TextField(blank=True, help_text='List of ingredients in English', verbose_name='Ingredients (English)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('image', models.URLField(blank=True, help_text='URL to dish image (for now, can be migrated to FileField later)', max_length=500, verbose_name='Image URL')),
                ('active', models.BooleanField(default=True, help_text='Whether this dish is currently available for menu planning', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='menu.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'ordering': ['category__order', 'category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity planned for production (nullable for flexibility)', null=True, verbose_name='Planned Quantity')),
                ('produced_quantity', models.PositiveIntegerField(default=0, help_text='Actual quantity produced', verbose_name='Produced Quantity')),
                ('available', models.BooleanField(default=True, help_text='Whether this dish is currently available for ordering', verbose_name='Available')),
                ('sold_out', models.BooleanField(default=False, help_text='Whether this dish has been sold out', verbose_name='Sold Out')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.dailymenu', verbose_name='Daily Menu')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_menu_entries', to='menu.dish', verbose_name='Dish')),
            ],
            options={
                'verbose_name': 'Daily Menu Dish',
                'verbose_name_plural': 'Daily Menu Dishes',
                'ordering': ['dish__category__order', 'dish__category', 'dish__name_en'],
                'unique_together': {('daily_menu', 'dish')},
            },
        ),
    ]
