# Generated by Django 5.0.1 on 2025-12-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload dish image', null=True, upload_to='dishes/', verbose_name='Image'),
        ),
    ]
