# Generated by Django 5.0.1 on 2025-12-25 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='half_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in EUR for half size (optional, mainly for soups)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Half Size)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in EUR for full size', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (Full Size)'),
        ),
    ]
