# Generated by Django 5.0.1 on 2025-12-25 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_half_price_alter_dish_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lt', models.CharField(help_text='e.g., Kompleksas 1', max_length=200, verbose_name='Name (Lithuanian)')),
                ('name_en', models.CharField(help_text='e.g., Complex 1', max_length=200, verbose_name='Name (English)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for the complex in EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('active', models.BooleanField(default=True, help_text='Whether this complex is currently available', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complex',
                'verbose_name_plural': 'Complexes',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='ComplexDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soup_size', models.CharField(choices=[('half', 'Half'), ('full', 'Full')], default='half', help_text='Size of the soup (half or full)', max_length=10, verbose_name='Soup Size')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display within the complex')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_options', to='menu.complex', verbose_name='Complex')),
                ('main_dish', models.ForeignKey(help_text='Main dish for this complex', on_delete=django.db.models.deletion.PROTECT, related_name='complex_main_options', to='menu.dish', verbose_name='Main Dish')),
                ('soup', models.ForeignKey(help_text='Soup dish for this complex', on_delete=django.db.models.deletion.PROTECT, related_name='complex_soup_options', to='menu.dish', verbose_name='Soup')),
            ],
            options={
                'verbose_name': 'Complex Dish Option',
                'verbose_name_plural': 'Complex Dish Options',
                'ordering': ['complex__order', 'complex', 'order'],
                'unique_together': {('complex', 'soup', 'soup_size', 'main_dish')},
            },
        ),
    ]
