# Generated by Django 5.0.1 on 2025-12-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_complex_complexdish'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexdish',
            name='main_dish_type',
            field=models.CharField(choices=[('main', 'Main Dish'), ('main_light', 'Main Light Dish')], default='main', help_text='Type of main dish (main dish or main light dish)', max_length=20, verbose_name='Main Dish Type'),
        ),
        migrations.AlterUniqueTogether(
            name='complexdish',
            unique_together={('complex', 'soup_size', 'main_dish_type')},
        ),
        migrations.RemoveField(
            model_name='complexdish',
            name='main_dish',
        ),
        migrations.RemoveField(
            model_name='complexdish',
            name='soup',
        ),
    ]
