# Generated by Django 5.0.1 on 2025-12-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_complexdish_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complexdish',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='complexdish',
            name='include_drink',
            field=models.BooleanField(default=False, help_text='Whether to include a drink from the Drinks category', verbose_name='Include Drink'),
        ),
        migrations.AlterUniqueTogether(
            name='complexdish',
            unique_together={('complex', 'soup_size', 'main_dish_type', 'include_drink')},
        ),
    ]
