# Generated by Django 5.0.1 on 2025-12-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_complexdish_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexdish',
            name='soup_size',
            field=models.CharField(choices=[('none', 'None'), ('half', 'Half'), ('full', 'Full')], default='half', help_text='Size of the soup (half or full)', max_length=10, verbose_name='Soup Size'),
        ),
    ]
