# Generated by Django 5.0.1 on 2025-12-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_complexdish_soup_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexdish',
            name='main_dish_type',
            field=models.CharField(choices=[('main', 'Main Dish'), ('main_light', 'Main Light Dish'), ('pizza', 'Pizza')], default='main', help_text='Type of main dish (main dish or main light dish)', max_length=20, verbose_name='Main Dish Type'),
        ),
    ]
