# Generated by Django 5.0.1 on 2025-12-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_complexdish_main_dish_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lt', models.CharField(max_length=100, verbose_name='Name (Lithuanian)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category for this subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category', 'order', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional subcategory (e.g., Beer, Wine, Lemonade for Drinks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='menu.subcategory', verbose_name='Subcategory'),
        ),
    ]
