# Generated by Django 5.0.10 on 2026-01-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_subcategory_dish_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenuComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True, help_text='Whether this complex is currently available for ordering', verbose_name='Available')),
                ('sold_out', models.BooleanField(default=False, help_text='Whether this complex has been sold out', verbose_name='Sold Out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='menu.complex', verbose_name='Complex')),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='menu.dailymenu', verbose_name='Daily Menu')),
            ],
            options={
                'verbose_name': 'Daily Menu Complex',
                'verbose_name_plural': 'Daily Menu Complexes',
                'ordering': ['complex__order', 'complex__name_en'],
                'unique_together': {('daily_menu', 'complex')},
            },
        ),
    ]
